//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ServerToclientUpdate
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShoppingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShoppingEntities object using the connection string found in the 'ShoppingEntities' section of the application configuration file.
        /// </summary>
        public ShoppingEntities() : base("name=ShoppingEntities", "ShoppingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoppingEntities object.
        /// </summary>
        public ShoppingEntities(string connectionString) : base(connectionString, "ShoppingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoppingEntities object.
        /// </summary>
        public ShoppingEntities(EntityConnection connection) : base(connection, "ShoppingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerCard> CustomerCards
        {
            get
            {
                if ((_CustomerCards == null))
                {
                    _CustomerCards = base.CreateObjectSet<CustomerCard>("CustomerCards");
                }
                return _CustomerCards;
            }
        }
        private ObjectSet<CustomerCard> _CustomerCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCollection> ItemCollections
        {
            get
            {
                if ((_ItemCollections == null))
                {
                    _ItemCollections = base.CreateObjectSet<ItemCollection>("ItemCollections");
                }
                return _ItemCollections;
            }
        }
        private ObjectSet<ItemCollection> _ItemCollections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemPurchased> ItemPurchaseds
        {
            get
            {
                if ((_ItemPurchaseds == null))
                {
                    _ItemPurchaseds = base.CreateObjectSet<ItemPurchased>("ItemPurchaseds");
                }
                return _ItemPurchaseds;
            }
        }
        private ObjectSet<ItemPurchased> _ItemPurchaseds;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerCards(CustomerCard customerCard)
        {
            base.AddObject("CustomerCards", customerCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCollections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCollections(ItemCollection itemCollection)
        {
            base.AddObject("ItemCollections", itemCollection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemPurchaseds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemPurchaseds(ItemPurchased itemPurchased)
        {
            base.AddObject("ItemPurchaseds", itemPurchased);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingModel", Name="CustomerCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerCard object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CustomerCard CreateCustomerCard(global::System.Int32 id)
        {
            CustomerCard customerCard = new CustomerCard();
            customerCard.Id = id;
            return customerCard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private global::System.String _CardNumber;
        partial void OnCardNumberChanging(global::System.String value);
        partial void OnCardNumberChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingModel", Name="ItemCollection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCollection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCollection object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ItemCollection CreateItemCollection(global::System.Int32 id)
        {
            ItemCollection itemCollection = new ItemCollection();
            itemCollection.Id = id;
            return itemCollection;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private Nullable<global::System.Int32> _Stock;
        partial void OnStockChanging(Nullable<global::System.Int32> value);
        partial void OnStockChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingModel", Name="ItemPurchased")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemPurchased : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemPurchased object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="itemId">Initial value of the ItemId property.</param>
        public static ItemPurchased CreateItemPurchased(global::System.Int32 id, global::System.Int32 itemId)
        {
            ItemPurchased itemPurchased = new ItemPurchased();
            itemPurchased.Id = id;
            itemPurchased.ItemId = itemId;
            return itemPurchased;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                OnItemIdChanging(value);
                ReportPropertyChanging("ItemId");
                _ItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemId");
                OnItemIdChanged();
            }
        }
        private global::System.Int32 _ItemId;
        partial void OnItemIdChanging(global::System.Int32 value);
        partial void OnItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerCardId
        {
            get
            {
                return _CustomerCardId;
            }
            set
            {
                OnCustomerCardIdChanging(value);
                ReportPropertyChanging("CustomerCardId");
                _CustomerCardId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerCardId");
                OnCustomerCardIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerCardId;
        partial void OnCustomerCardIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerCardIdChanged();

        #endregion

    
    }

    #endregion

    
}
